spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=Asia/Shanghai
    username: root
    password: root

  # 环境设置：dev、test、prod
  profiles:
    active: dev
    #bynatis日志
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    port: 6379
    host: 127.0.0.1
  application:
    name: ucenter
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8160
wx:
  open:
    app_id: wxed9954c01bb89b47
    app_secret: a7482517235173ddb4083788de60b90e
    redirecturl: http://localhost:8160/api/ucenter/wx/callback